DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM marketplace_accounts WHERE NOT legacy_unassigned) OR EXISTS(SELECT 1 FROM business_identities WHERE NOT legacy_unassigned) THEN
  RAISE EXCEPTION 'Cannot downgrade real seller account data; retain provenance and use a forward migration';
 END IF;
END $$;
DROP TRIGGER sku_mappings_immutable_account ON sku_mappings;
DROP TRIGGER source_files_immutable_account ON source_files;
DROP TRIGGER processing_jobs_immutable_account ON processing_jobs;
DROP TRIGGER marketplace_orders_immutable_account ON marketplace_orders;
DROP TRIGGER batches_immutable_account ON batches;
DROP TRIGGER batch_members_immutable_account ON batch_members;
DROP TRIGGER cancellations_immutable_account ON cancellations;
DROP TRIGGER return_cases_immutable_account ON return_cases;
DROP TRIGGER marketplace_order_documents_immutable_account ON marketplace_order_documents;
DROP TRIGGER processing_jobs_inherit_account ON processing_jobs;
DROP TRIGGER marketplace_orders_inherit_account ON marketplace_orders;
DROP TRIGGER batch_members_inherit_account ON batch_members;
DROP TRIGGER cancellations_inherit_account ON cancellations;
DROP TRIGGER return_cases_inherit_account ON return_cases;
DROP TRIGGER marketplace_order_documents_inherit_account ON marketplace_order_documents;
DROP TRIGGER business_identities_guard ON business_identities;
DROP TRIGGER marketplace_accounts_guard ON marketplace_accounts;
DROP FUNCTION immutable_marketplace_provenance();
DROP FUNCTION inherit_marketplace_account();
DROP FUNCTION guard_marketplace_account_identity();
DROP INDEX marketplace_orders_account_created_idx;
DROP INDEX processing_jobs_account_created_idx;
DROP INDEX batches_account_created_idx;
DROP INDEX sku_mappings_active_lookup_unique;
DROP INDEX processing_jobs_company_account_upload_idempotency_unique;
DROP INDEX marketplace_orders_awb_unique;
DROP INDEX marketplace_orders_order_id_unique;
ALTER TABLE source_files DROP CONSTRAINT source_files_account_hash_unique;
ALTER TABLE batch_members DROP CONSTRAINT batch_members_batch_account_fk;
ALTER TABLE marketplace_order_documents DROP CONSTRAINT marketplace_order_documents_source_account_fk;
ALTER TABLE marketplace_orders DROP CONSTRAINT marketplace_orders_job_source_account_fk;
ALTER TABLE marketplace_orders DROP CONSTRAINT marketplace_orders_source_account_fk;
ALTER TABLE processing_jobs DROP CONSTRAINT processing_jobs_source_account_fk;
ALTER TABLE processing_jobs DROP CONSTRAINT processing_jobs_source_identity_unique;
ALTER TABLE batch_members DROP CONSTRAINT batch_members_order_account_fk;
ALTER TABLE batch_members DROP COLUMN marketplace_account_id;
ALTER TABLE cancellations DROP CONSTRAINT cancellations_order_account_fk;
ALTER TABLE cancellations DROP COLUMN marketplace_account_id;
ALTER TABLE return_cases DROP CONSTRAINT return_cases_order_account_fk;
ALTER TABLE return_cases DROP COLUMN marketplace_account_id;
ALTER TABLE marketplace_order_documents DROP CONSTRAINT marketplace_order_documents_order_account_fk;
ALTER TABLE marketplace_order_documents DROP COLUMN marketplace_account_id;
ALTER TABLE sku_mappings DROP CONSTRAINT sku_mappings_account_marketplace_fk;
ALTER TABLE sku_mappings DROP CONSTRAINT sku_mappings_account_identity_unique;
ALTER TABLE sku_mappings DROP COLUMN marketplace_account_id;
ALTER TABLE source_files DROP CONSTRAINT source_files_account_marketplace_fk;
ALTER TABLE source_files DROP CONSTRAINT source_files_account_identity_unique;
ALTER TABLE source_files DROP COLUMN marketplace_account_id;
ALTER TABLE processing_jobs DROP CONSTRAINT processing_jobs_account_marketplace_fk;
ALTER TABLE processing_jobs DROP CONSTRAINT processing_jobs_account_identity_unique;
ALTER TABLE processing_jobs DROP COLUMN marketplace_account_id;
ALTER TABLE marketplace_orders DROP CONSTRAINT marketplace_orders_account_marketplace_fk;
ALTER TABLE marketplace_orders DROP CONSTRAINT marketplace_orders_account_identity_unique;
ALTER TABLE marketplace_orders DROP COLUMN marketplace_account_id;
ALTER TABLE batches DROP CONSTRAINT batches_account_marketplace_fk;
ALTER TABLE batches DROP CONSTRAINT batches_account_identity_unique;
ALTER TABLE batches DROP COLUMN marketplace_account_id;
CREATE UNIQUE INDEX sku_mappings_active_lookup_unique ON sku_mappings(company_id,marketplace_key,sku) WHERE status='active';
ALTER TABLE source_files ADD CONSTRAINT source_files_company_id_marketplace_key_sha256_key UNIQUE(company_id,marketplace_key,sha256);
CREATE UNIQUE INDEX processing_jobs_company_marketplace_upload_idempotency_unique ON processing_jobs(company_id,marketplace_key,upload_idempotency_key) WHERE upload_idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX marketplace_orders_awb_unique ON marketplace_orders(company_id,marketplace_key,awb) WHERE awb IS NOT NULL AND status<>'duplicate';
CREATE UNIQUE INDEX marketplace_orders_order_id_unique ON marketplace_orders(company_id,marketplace_key,marketplace_order_id) WHERE marketplace_order_id IS NOT NULL AND status<>'duplicate';
DROP TABLE marketplace_accounts;
DROP TABLE business_identities;
DELETE FROM role_permissions WHERE permission_key IN ('marketplace_accounts.view','marketplace_accounts.manage');
DELETE FROM permissions WHERE key IN ('marketplace_accounts.view','marketplace_accounts.manage');
-- JioMart is safe additive registry data and is retained on downgrade.
