"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { InventoryBalance, InventoryTransaction, Reservation, inventoryAPI } from "@/api/inventory";

export function InventoryWorkspace() {
  const [balances, setBalances] = useState<InventoryBalance[]>([]); const [transactions, setTransactions] = useState<InventoryTransaction[]>([]); const [reservations, setReservations] = useState<Reservation[]>([]);
  const [product, setProduct] = useState(""); const [type, setType] = useState(""); const [available, setAvailable] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const [b,t,r]=await Promise.all([inventoryAPI.balances(),inventoryAPI.transactions(product,type),inventoryAPI.reservations()]);setBalances(b.inventory);setTransactions(t.transactions);setReservations(r.reservations); },[product,type]);
  useEffect(()=>{load().catch(()=>setAvailable(false));},[load]);
  const names=useMemo(()=>Object.fromEntries(balances.map((b)=>[b.product_id,`${b.internal_code} · ${b.product_name}`])),[balances]);
  async function command(event:FormEvent<HTMLFormElement>,kind:"stock"|"adjust") { event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const input={product_id:String(data.get("product")),quantity:Number(data.get("quantity")),reason:String(data.get("reason")),idempotency_key:crypto.randomUUID()};if(kind==="adjust"&&!window.confirm(`Record inventory adjustment of ${input.quantity}?`))return;setBusy(true);setError("");try{if(kind==="stock")await inventoryAPI.stockIn(input);else await inventoryAPI.adjust(input);form.reset();await load();}catch(cause){setError(message(cause));}finally{setBusy(false);} }
  async function outbound(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget;const batch=String(new FormData(form).get("batch"));try{await inventoryAPI.confirmOutbound(batch,crypto.randomUUID());form.reset();await load();}catch(cause){setError(message(cause));}finally{setBusy(false)}}
  async function reserve(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget;const d=new FormData(form);try{await inventoryAPI.reserve({product_id:String(d.get("product")),quantity:Number(d.get("quantity")),reason:String(d.get("reason")),source_type:String(d.get("source_type")),source_id:String(d.get("source_id")),idempotency_key:crypto.randomUUID()});form.reset();await load();}catch(cause){setError(message(cause));}finally{setBusy(false)}}
  async function release(item:Reservation){const reason=window.prompt("Reason for releasing this reservation?");if(!reason?.trim())return;setBusy(true);setError("");try{await inventoryAPI.release(item.id,reason.trim(),crypto.randomUUID());await load();}catch(cause){setError(message(cause));}finally{setBusy(false)}}
  if(!available)return <section className="panel inventory"><h2>Inventory</h2><p className="muted">Inventory is not available for this account.</p></section>;
  return <section className="inventory"><div className="product-heading"><div><p className="eyebrow">Phase 5</p><h2>Inventory</h2><p className="muted">On-hand, reserved, and available stock from the centralized ledger.</p></div><button className="secondary" disabled={busy} onClick={()=>load().catch((cause)=>setError(message(cause)))}>Refresh</button></div>{error&&<p className="error" role="alert">{error}</p>}
    <section className="panel inventory-table"><div className="status-line"><h2>Current stock</h2><span className="status">{balances.length} products</span></div><div className="table-scroll"><table><thead><tr><th>Product</th><th>On-hand</th><th>Reserved</th><th>Available</th></tr></thead><tbody>{balances.map((b)=><tr key={b.product_id}><td><strong>{b.internal_code}</strong><small>{b.product_name}</small></td><td>{b.on_hand}</td><td>{b.reserved}</td><td>{b.available}</td></tr>)}</tbody></table></div></section>
    <div className="inventory-actions"><InventoryForm title="Stock in" submit="Add stock" balances={balances} busy={busy} onSubmit={(e)=>command(e,"stock")} positive/><InventoryForm title="Adjustment" submit="Record adjustment" balances={balances} busy={busy} onSubmit={(e)=>command(e,"adjust")} /><form className="panel stack" onSubmit={outbound}><h2>Confirm outbound</h2><p className="muted">Deduct a ready batch once. Printing and reprinting never deduct stock.</p><label>Batch ID<input name="batch" required /></label><button disabled={busy}>Confirm ecommerce outbound</button></form></div>
    <section className="panel inventory-history"><div className="status-line"><div><h2>Transaction history</h2><p className="muted">Immutable inventory movements, newest first.</p></div><div className="history-filters"><select aria-label="Filter product" value={product} onChange={(e)=>setProduct(e.target.value)}><option value="">All products</option>{balances.map((b)=><option key={b.product_id} value={b.product_id}>{b.internal_code}</option>)}</select><select aria-label="Filter transaction type" value={type} onChange={(e)=>setType(e.target.value)}><option value="">All types</option>{["stock_in","manual_adjustment","correction","ecommerce_out"].map((v)=><option key={v}>{v}</option>)}</select></div></div><ul>{transactions.map((t)=><li key={t.id}><span><strong>{names[t.product_id]??t.product_id}</strong><small>{t.transaction_type} · {t.reason} · {new Date(t.created_at).toLocaleString()}</small></span><strong className={t.quantity_delta>0?"positive":"negative"}>{t.quantity_delta>0?"+":""}{t.quantity_delta}</strong></li>)}</ul></section>
    <div className="inventory-actions"><form className="panel stack" onSubmit={reserve}><h2>Create reservation</h2><label>Product<ProductSelect balances={balances}/></label><label>Quantity<input name="quantity" type="number" min="1" required/></label><label>Reason<input name="reason" maxLength={500} required/></label><label>Source type<input name="source_type" maxLength={100} placeholder="consignment" required/></label><label>Source ID<input name="source_id" maxLength={200} required/></label><button disabled={busy}>Reserve stock</button></form><section className="panel reservation-list"><h2>Reservations</h2><ul>{reservations.map((r)=><li key={r.id}><span><strong>{names[r.product_id]??r.product_id} · {r.quantity}</strong><small>{r.source_type}/{r.source_id} · {r.status}</small></span>{r.status==="active"&&<button disabled={busy} onClick={()=>release(r)}>Release</button>}</li>)}</ul></section></div>
  </section>;
}
function InventoryForm({title,submit,balances,busy,onSubmit,positive=false}:{title:string;submit:string;balances:InventoryBalance[];busy:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;positive?:boolean}){return <form className="panel stack" onSubmit={onSubmit}><h2>{title}</h2><label>Product<ProductSelect balances={balances}/></label><label>Quantity<input name="quantity" type="number" min={positive?1:undefined} required/></label><label>Reason<input name="reason" maxLength={500} required/></label><button disabled={busy}>{submit}</button></form>}
function ProductSelect({balances}:{balances:InventoryBalance[]}){return <select name="product" required><option value="">Select product</option>{balances.map((b)=><option key={b.product_id} value={b.product_id}>{b.internal_code} · {b.product_name}</option>)}</select>}
function message(cause:unknown){return cause instanceof Error?cause.message:"Something went wrong"}
