"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Marketplace, Product, Resolution, SKUMapping, productAPI } from "@/api/products";

export function ProductMaster() {
  const [products, setProducts] = useState<Product[]>([]); const [mappings, setMappings] = useState<SKUMapping[]>([]); const [marketplaces, setMarketplaces] = useState<Marketplace[]>([]);
  const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [resolution, setResolution] = useState<Resolution | null>(null); const [available, setAvailable] = useState(true);
  const load = useCallback(async () => { const [p,m,markets]=await Promise.all([productAPI.products(query),productAPI.mappings(),productAPI.marketplaces()]); setProducts(p.products); setMappings(m.sku_mappings); setMarketplaces(markets.marketplaces); }, [query]);
  useEffect(() => { load().catch(() => setAvailable(false)); }, [load]);

  async function createProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=new FormData(form); setError(""); try { await productAPI.createProduct({ internal_code:String(data.get("code")),name:String(data.get("name")),brand:value(data,"brand"),variant:value(data,"variant"),size:null,pack_type:null,unit_count:numberValue(data,"units"),status:"active" }); form.reset(); await load(); } catch(cause){setError(message(cause));} }
  async function train(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=new FormData(form); setError(""); try { await productAPI.createMapping({marketplace_key:String(data.get("marketplace")),product_id:String(data.get("product")),sku:String(data.get("sku")),quantity_multiplier:numberValue(data,"multiplier") ?? 1,interpretation_metadata:{},status:"active"}); form.reset(); await load(); } catch(cause){setError(message(cause));} }
  async function resolve(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); setError(""); try { setResolution(await productAPI.resolve(String(data.get("marketplace")),String(data.get("sku")))); } catch(cause){setError(message(cause));} }
  if (!available) return <section className="panel product-master"><h2>Product Master</h2><p className="muted">Product access is not available for this account.</p></section>;
  return <section className="product-master"><div className="product-heading"><div><p className="eyebrow">Phase 2</p><h2>Product Master</h2><p className="muted">Canonical products and exact marketplace SKU training.</p></div><input aria-label="Search products" placeholder="Search code or name" value={query} onChange={(event)=>setQuery(event.target.value)} /></div>
    {error && <p className="error" role="alert">{error}</p>}<div className="grid">
      <section className="panel"><h2>Create product</h2><form className="stack" onSubmit={createProduct}><label>Internal code<input name="code" required /></label><label>Name<input name="name" required /></label><label>Brand<input name="brand" /></label><label>Variant<input name="variant" /></label><label>Unit count<input name="units" type="number" min="1" /></label><button>Create product</button></form></section>
      <section className="panel"><h2>Products</h2><ul>{products.map((item)=><li key={item.id}><span><strong>{item.internal_code}</strong> · {item.name}<small>{[item.brand,item.variant].filter(Boolean).join(" · ") || "No structured attributes"}</small></span><button onClick={()=>productAPI.updateProduct(item.id,{...withoutID(item),status:item.status==="active"?"inactive":"active"}).then(load).catch((cause)=>setError(message(cause)))}>{item.status}</button></li>)}</ul></section>
      <section className="panel"><h2>Train SKU mapping</h2><form className="stack" onSubmit={train}><label>Marketplace<select name="marketplace" required>{marketplaces.map((item)=><option key={item.key} value={item.key}>{item.display_name}</option>)}</select></label><label>Exact SKU<input name="sku" required /></label><label>Product<select name="product" required>{products.filter((item)=>item.status==="active").map((item)=><option key={item.id} value={item.id}>{item.internal_code} · {item.name}</option>)}</select></label><label>Quantity multiplier<input name="multiplier" type="number" min="1" defaultValue="1" required /></label><button>Save training</button></form></section>
      <section className="panel"><h2>Test exact resolution</h2><form className="stack" onSubmit={resolve}><label>Marketplace<select name="marketplace" required>{marketplaces.map((item)=><option key={item.key} value={item.key}>{item.display_name}</option>)}</select></label><label>Exact SKU<input name="sku" required /></label><button>Resolve SKU</button></form>{resolution && <p className={resolution.status==="resolved"?"result-ok":"result-unresolved"}>{resolution.status==="resolved"?`${resolution.product?.internal_code} · ${resolution.product?.name}`:"Unresolved — training is required"}</p>}</section>
      <section className="panel span-two"><h2>SKU mappings</h2><ul>{mappings.map((item)=><li key={item.id}><span><strong>{item.marketplace_key}</strong> · {item.sku}<small>{products.find((product)=>product.id===item.product_id)?.internal_code ?? item.product_id} · multiplier {item.quantity_multiplier}</small></span><button onClick={()=>productAPI.updateMapping(item.id,{...withoutMappingID(item),status:item.status==="active"?"inactive":"active"}).then(load).catch((cause)=>setError(message(cause)))}>{item.status}</button></li>)}</ul></section>
    </div></section>;
}

function value(data:FormData,key:string){const v=String(data.get(key)).trim();return v||null;} function numberValue(data:FormData,key:string){const v=String(data.get(key)).trim();return v?Number(v):null;}
function withoutID(item:Product){return {internal_code:item.internal_code,name:item.name,brand:item.brand,variant:item.variant,size:item.size,pack_type:item.pack_type,unit_count:item.unit_count,status:item.status};}
function withoutMappingID(item:SKUMapping){return {marketplace_key:item.marketplace_key,product_id:item.product_id,sku:item.sku,quantity_multiplier:item.quantity_multiplier,interpretation_metadata:item.interpretation_metadata,status:item.status};}
function message(cause:unknown){return cause instanceof Error?cause.message:"Something went wrong";}
